[config]
tt_size = 11141120 # 255 * 1024 * 1024 / 24 (255MB) 
qsearch_depth = 15
rfp_depth = 11
rfp_base_margin = 55
rfp_reduction_improving = 23
nmp_depth = 5
nmp_margin = 18
nmp_divisor = 6
nmp_divisor_improving = 5
lmp_move_margin = 2
lmp_depth_factor = 5
lmr_depth = 12
lmr_move_margin = 9
lmr_quiet_margin = 2.74
lmr_quiet_divisor = 1.65
lmr_base_margin = 0.25
lmr_base_divisor = 1.70
mo_tt_entry_value = 233
mo_capture_value = 60
mo_killer_value = 76
tc_time_divisor = 8
tc_elapsed_factor = 5
